#%RAML 1.0 Trait

description: Client ID enforcement policy for authenticating the consumer
usage: Apply to all operations

headers:
  X-ClientID:
    description: The Client ID of the consumer
    example: e5f19124663b428bda269a3b53b722ef
    type: string
    required: false
  X-ClientSecret:
    description: The Client Secret of the consumer
    example: ea1b8baf121f4612A29C096C8AA0C6D4
    type: string
    required: false
